// <auto-generated />
using System;
using ApprovementWorkflowSample.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApprovementWorkflowSample.Migrations
{
    [DbContext(typeof(ApprovementWorkflowContext))]
    partial class ApprovementWorkflowContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("ApprovementWorkflowSample.Applications.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("mail");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_update_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Organization")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("organization");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.Approver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("date")
                        .HasColumnName("approved_date");

                    b.Property<int>("ApproverGroupId")
                        .HasColumnType("int")
                        .HasColumnName("approver_group_id");

                    b.Property<int>("ApproverRoleId")
                        .HasColumnType("int")
                        .HasColumnName("approver_role_id");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_update_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ApproverGroupId");

                    b.HasIndex("ApproverRoleId");

                    b.ToTable("Approvers");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.ApproverGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int")
                        .HasColumnName("workflow_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId");

                    b.ToTable("ApproverGroups");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.ApproverRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ApproverRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Author"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Checker"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Approver"
                        });
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("date")
                        .HasColumnName("approved_date");

                    b.Property<DateTimeOffset>("LastUpdateDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("last_update_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<int>("WorkflowTypeId")
                        .HasColumnType("int")
                        .HasColumnName("workflow_type_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowTypeId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.WorkflowType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("WorkflowType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "WorkflowTypeA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "WorkflowTypeA"
                        });
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.Approver", b =>
                {
                    b.HasOne("ApprovementWorkflowSample.Approvements.ApproverGroup", "ApproverGroup")
                        .WithMany("Approvers")
                        .HasForeignKey("ApproverGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApprovementWorkflowSample.Approvements.ApproverRole", "ApproverRole")
                        .WithMany("Approvers")
                        .HasForeignKey("ApproverRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverGroup");

                    b.Navigation("ApproverRole");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.ApproverGroup", b =>
                {
                    b.HasOne("ApprovementWorkflowSample.Approvements.Workflow", "Workflow")
                        .WithMany("ApproverGroups")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.Workflow", b =>
                {
                    b.HasOne("ApprovementWorkflowSample.Approvements.WorkflowType", "WorkflowType")
                        .WithMany("Workflows")
                        .HasForeignKey("WorkflowTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowType");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.ApproverGroup", b =>
                {
                    b.Navigation("Approvers");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.ApproverRole", b =>
                {
                    b.Navigation("Approvers");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.Workflow", b =>
                {
                    b.Navigation("ApproverGroups");
                });

            modelBuilder.Entity("ApprovementWorkflowSample.Approvements.WorkflowType", b =>
                {
                    b.Navigation("Workflows");
                });
#pragma warning restore 612, 618
        }
    }
}
